### ISSUE TITLE
Could you document the way to use authCodeGrant properly, cant find a way to use it

### ISSUE THREAD

**Issue by jhonatanTeixeira** [thomseddon/node-oauth2-server#191]
Could you document the way to use authCodeGrant properly, cant find a way to use it

Thanks

**Comment by xqjibz** [comment]
+1, I can't seem to find a valid example.  The example  [here](https://github.com/thomseddon/node-oauth2-server/blob/master/examples/postgresql/index.js#L59-L73) does not appear to work, though, I'm not completely sure I'm using it right.

**Comment by fayimora** [comment]
:+1: it would be nice to actually have examples on how to use all the grants. curl links or whatever should be sufficient.

cc @thomseddon

**Comment by thomseddon** [comment]
@xqjibz How is that example not working for you?

**Comment by xqjibz** [comment]
@thomseddon I think the example wasn't clear for the use case I was doing.  Which could have been my simple misunderstanding of Oauth2 in general.  I did eventually get this all working, though, I've moved onto another project since this time.  Basically, I was trying to do an authorization example, where I already knew the identity of the client requesting authorization, what I ran into sort of lead me down a path to comment here, though, I didn't have anything specific at the time, and still don't.  I'm chalking this one up to my misunderstanding of the Oauth2 process.

**Comment by fb13** [comment]
Is it normal to use more then one of the grant types in the same app? I want the user to be able to provide his credentials in my native smartphone app (password grant type), but I also want other applications to get access to the API (client credentials grant type). Is it right to use different grant types in one app?

cc @thomseddon

**Comment by thomseddon** [comment]
OK no worries - it's not easy to get your head around

@fb13 Yes it's quite normal to support different auth flows for different clients in the same app :)
