### ISSUE TITLE
Only allow application/x-www-form-urlencoded?

### ISSUE THREAD

**Issue by jamierumbelow** [thomseddon/node-oauth2-server#199]
Is there a particular reason (e.g. the oauth specs) why the library only allows `application/x-www-form-urlencoded` requests? In the interests of consistency in my API, I'd prefer to allow JSON requests too.

**Comment by philplckthun** [comment]
This looks really unnecessary, because it restricts the whole thing to the `bodyParser.urlencoded` middleware, as compared to for example Passport.js, which doesn't test for this and just deals with `req.body` instead.

If there's a need to prevent any empty `req.body` objects from passing through, why is this not just testing the `req.body` object itself?

The checks using `req.is` should be removed altogether IMHO.

**Comment by ognus** [comment]
+1 I am building RESTful API and don't really need x-www-form-urlencoded

**Comment by thomseddon** [comment]
Yep sorry, just following the spec, there is a work-around here: https://github.com/thomseddon/node-oauth2-server/issues/92#issuecomment-50263592

**Comment by AndrewAskins** [comment]
@thomseddon from my reading of the spec it looked like x-www-form-urlencoded was just one option, not the requirement.
