### ISSUE TITLE
'this' is not set for getAccessToken but is for saveAccessToken

### ISSUE THREAD

**Issue by djMax** [thomseddon/node-oauth2-server#259]
My model is an instance of an object. The this pointer is not properly set for getAccessToken, but is set for saveAccessToken...

**Comment by lfk** [comment]
```
grant-types/authorization-code-grant-type.js
34:  if (!options.model.saveToken) {
201:      return this.model.saveToken(token, client, user);
                                                                                                                                                           
handlers/authenticate-handler.js
28:  if (!options.model.getAccessToken) {
198:  return Promise.try(this.model.getAccessToken, token)
```

Would doing `this.model.getAccessToken.bind(this.model)` solve the issue for you?

This type of invocation is used in multiple locations, not sure how it would impact the lib by adding it in one place or all places.

Just out of curiosity, are you using the model instance to store state? In my own implementation I've never had to rely on the model instance itself, since it boils down to database/model operations.

**Comment by djMax** [comment]
Yes, I suppose that would do it. I think it's more about us being consistent about whether binding will happen or won't... I was just compartmentalizing as a class for convenience and style - e.g. I have db connections and such that I pass into the constructor which make it slightly easier for me to mock things during testing...

**Comment by djMax** [comment]
#266
